apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-container
  labels:
    app: init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-container
  template:
    metadata:
      labels:
        app: init-container
    spec:
      containers:
      - name: init-container
        image: docker-registry.ujar.org/ujar/micro-k8s-bookingdb-init-container-service
        ports:
        - containerPort: 8080
        env:
        - name: DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: init-container
              key: datasource.url
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: init-container
              key: datasource.username
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: init-container
              key: datasource.password
        resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "1.0"
            memory: 300Mi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 50
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 50
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 5
      serviceAccountName: api-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: init-container
  labels:
    app: init-container
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: init-container
