# This configuration is intended for demo purpose
version: "3.8"
services:
  mysql:
    image: mysql:5.7.44
    container_name: bookingdemandapietl-demo-mysql
    restart: no
    environment:
      - MYSQL_DATABASE=demo_db
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
      - MYSQL_ROOT_PASSWORD=demo_root
      - TZ=UTC

  rabbitmq:
    container_name: bookingdemandapietl-demo-rabbitmq
    image: rabbitmq:management-alpine
    restart: no
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo

  bookingdemandapietl-init-container-service:
    image: "know-how.download/sample-booking-demand-api-etl-mix-init-container-service:latest"
    container_name: bookingdemandapietl-demo-init-container-service
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - mysql
    environment:
      - DATASOURCE_USERNAME=demo
      - DATASOURCE_PASSWORD=demo
      - DATASOURCE_URL=jdbc:mysql://bookingdemandapietl-demo-mysql:3306/demo_db

  bookingdemandapietl-dashboard-service:
    image: "know-how.download/sample-booking-demand-api-etl-mix-dashboard-service:latest"
    container_name: bookingdemandapietl-demo-dashboard-service
    restart: no
    depends_on:
      - mysql
      - rabbitmq
      - bookingdemandapietl-init-container-service
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_USERNAME=demo
      - DATASOURCE_PASSWORD=demo
      - DATASOURCE_URL=jdbc:mysql://bookingdemandapietl-demo-mysql:3306/demo_db
      - RABBITMQ_HOST=bookingdemandapietl-demo-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=demo
      - RABBITMQ_PASSWORD=demo

  bookingdemandapietl-importer-service:
    image: "know-how.download/sample-booking-demand-api-etl-mix-importer-service:latest"
    container_name: bookingdemandapietl-demo-importer-service
    restart: no
    depends_on:
      - mysql
      - rabbitmq
      - bookingdemandapietl-init-container-service
      - bookingdemandapietl-dashboard-service
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_USERNAME=demo
      - DATASOURCE_PASSWORD=demo
      - DATASOURCE_URL=jdbc:mysql://bookingdemandapietl-demo-mysql:3306/demo_db
      - RABBITMQ_HOST=bookingdemandapietl-demo-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=demo
      - RABBITMQ_PASSWORD=demo
