build :
  description : '@project.description@'
  relative-path : ${SWAGGER_RELATIVE_PATH:}
  version : '@project.version@'

git :
  commit : '@git.commit.id@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : importer-service
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    url : ${DATASOURCE_URL:jdbc:mysql://localhost:3306/sa_test_db?serverTimezone=UTC&rewriteBatchedStatements=true&characterEncoding=UTF-8}
    username : ${DATASOURCE_USERNAME:sa_test}
    password : ${DATASOURCE_PASSWORD:sa_test}
    driver-class-name : ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari :
      pool-name : Hikari
      auto-commit : false
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy : org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view : true
    properties :
      hibernate.jdbc.time_zone : UTC
      hibernate.id.new_generator_mappings : true
      hibernate.connection.provider_disables_autocommit : true
      hibernate.cache.use_second_level_cache : true
      hibernate.cache.use_query_cache : true
      hibernate.generate_statistics : false
      # modify batch size as necessary
      hibernate.jdbc.batch_size : 25
      hibernate.order_inserts : true
      hibernate.order_updates : true
      hibernate.query.fail_on_pagination_over_collection_fetch : true
      hibernate.query.in_clause_parameter_padding : true
    show-sql : false
  rabbitmq :
    host : ${RABBITMQ_HOST:localhost}
    port : ${RABBITMQ_PORT:5672}
    username : ${RABBITMQ_USERNAME:sa_test}
    password : ${RABBITMQ_PASSWORD:sa_test}
  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false

  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}

logging :
  level :
    ROOT :  ${LOGGING_LEVEL_ROOT:INFO}
    org.zalando.logbook.Logbook : TRACE

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful


logbook :
  exclude :
    - /actuator/**
    - /v3/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /metrics
  filter :
    enabled : true
  format :
    style : json
  obfuscate :
    headers :
      - Authorization
      - X-Secret
    parameters :
      - access_token
      - password
  minimum-status : ${MINIMUM_STATUS_LOG_BODY:400}

management :
  info :
    env :
      enabled : true
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      path-mapping :
        health : actuator/health
        prometheus : metrics
        info : info
      base-path : /
      exposure :
        include : health, prometheus, info
  endpoint :
    health :
      enabled : true
      show-details : always
    prometheus :
      enabled : true
    info :
      enabled : true

bookingdb :
  net-client :
    username : ${BOOLINGCOM_USERNAME:}
    password : ${BOOLINGCOM_PASSWORD:}
    api-host : distribution-xml.booking.com
    api-schema : https
    api-path : /{version}/{outputFormat}/{path}
    version : 2.6
    output-format : json
    connect-timeout : 5  # in sec.
    request-timeout : 20

  queues :
    import-exchange : ${IMPORT_JOBS_EXCHANGE:import-jobs-exchange}
    import-countries-queue : ${IMPORT_COUNTRIES_QUEUE:import-countries-queue}
    import-cities-queue : ${IMPORT_CITIES_QUEUE:import-cities-queue}
    import-hotels-queue : ${IMPORT_HOTELS_QUEUE:import-hotels-queue}
