build :
  description : '@project.description@'
  relative-path : ${SWAGGER_UI_RELATIVE_PATH:}
  version : '@project.version@'

git :
  commit : '@git.commit.id.abbrev@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : init-container-service
  liquibase :
    change-log : migrations/master.xml
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    url : ${DATASOURCE_URL:jdbc:mysql://localhost:3306/svc_testing_db?serverTimezone=UTC&rewriteBatchedStatements=true&characterEncoding=UTF-8}
    username : ${DATASOURCE_USERNAME:svc_testing}
    password : ${DATASOURCE_PASSWORD:svc_testing}
    driver-class-name : ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari :
      pool-name : Hikari
      auto-commit : false
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy : org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view : true
    properties :
      hibernate.jdbc.time_zone : UTC
      hibernate.id.new_generator_mappings : true
      hibernate.connection.provider_disables_autocommit : true
      hibernate.cache.use_second_level_cache : false
      hibernate.cache.use_query_cache : false
      hibernate.generate_statistics : false
      # modify batch size as necessary
      hibernate.jdbc.batch_size : 25
      hibernate.order_inserts : true
      hibernate.order_updates : true
      hibernate.query.fail_on_pagination_over_collection_fetch : true
      hibernate.query.in_clause_parameter_padding : true
    show-sql : false


  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}

logging :
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  info :
    env :
      enabled : true
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, prometheus, info
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    prometheus :
      enabled : true

springdoc :
  show-actuator : false
  swagger-ui :
    config-url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs/swagger-config
    url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs
