apiVersion : v1
kind : ConfigMap
metadata :
  name : importer-service
data :
  swagger-relative-path : /importer/
  datasource-url : jdbc:mysql://mysql:3306/sa_test_db
  rabbitmq-host : rabbitmq
  rabbitmq-port : "5672"
