apiVersion : apps/v1
kind : Deployment
metadata :
  name : importer-service
  labels :
    app : importer-service
spec :
  replicas : 1
  selector :
    matchLabels :
      app : importer-service
  template :
    metadata :
      labels :
        app : importer-service
    spec :
      containers :
        - name : importer-service
          image : docker-registry.ujar.org/ujar/micro-k8s-bookingdb-importer-service:latest
          ports :
            - containerPort : 8080
          env :
            - name : SWAGGER_RELATIVE_PATH
              valueFrom :
                configMapKeyRef :
                  name : importer-service
                  key : swagger-relative-path
            - name : LOGGING_LEVEL_ROOT
              valueFrom :
                configMapKeyRef :
                  name : importer-service
                  key : logging-level-root
            - name : DATASOURCE_URL
              valueFrom :
                configMapKeyRef :
                  name : importer-service
                  key : datasource-url
            - name : DATASOURCE_USERNAME
              valueFrom :
                secretKeyRef :
                  name : importer-service
                  key : datasource-username
            - name : DATASOURCE_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : importer-service
                  key : datasource-password
            - name : RABBITMQ_HOST
              valueFrom :
                configMapKeyRef :
                  name : importer-service
                  key : rabbitmq-host
            - name : RABBITMQ_PORT
              valueFrom :
                configMapKeyRef :
                  name : importer-service
                  key : rabbitmq-port
            - name : RABBITMQ_USERNAME
              valueFrom :
                secretKeyRef :
                  name : importer-service
                  key : rabbitmq-username
            - name : RABBITMQ_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : importer-service
                  key : rabbitmq-password
          resources :
            requests :
              cpu : "0.2"
              memory : 300Mi
            limits :
              cpu : "1.0"
              memory : 300Mi
          readinessProbe :
            tcpSocket :
              port : 8080
            initialDelaySeconds : 50
            timeoutSeconds : 2
            periodSeconds : 20
            failureThreshold : 5
          livenessProbe :
            tcpSocket :
              port : 8080
            initialDelaySeconds : 50
            timeoutSeconds : 2
            periodSeconds : 20
            failureThreshold : 5
      serviceAccountName : api-service-account
---
apiVersion : v1
kind : Service
metadata :
  name : importer-service
  labels :
    app : importer-service
spec :
  ports :
    - port : 8080
      targetPort : 8080
      protocol : TCP
  selector :
    app : importer-service
