kind : pipeline
name : CI

type : docker

trigger :
  event :
    - push
    - tag

volumes :
  - name : m2cache
    host :
      path : /app/.m2
steps :

  - name : build-and-publish-snapshot-jar
    image : docker-registry.c2a2.com/ujar/maven:3-openjdk-17-slim
    pull : if-not-exists
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DATASOURCE_DRIVER : com.mysql.cj.jdbc.Driver
      DATASOURCE_URL : jdbc:mysql://db:3306/sa_test_db?serverTimezone=UTC&rewriteBatchedStatements=true&characterEncoding=UTF-8
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
      SONAR_HOST :
        from_secret : SONAR_HOST
      SONAR_TOKEN :
        from_secret : SONAR_TOKEN
    commands :
      - mvn clean compile test-compile -P default -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      #- mvn pmd:check -P default -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      #- mvn com.github.spotbugs:spotbugs-maven-plugin:check -P default -Dspotbugs.xmlOutput=true -Dspotbugs.failOnError=true -Dspotbugs.includeTests=true -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=ujar-org:bs-dst-k8s-bookingdb -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn deploy -P default -DskipTests=true -Dcheckstyle.skip=true -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD -DaltDeploymentRepository=ujar-snapshots-repository::default::https://nexus.c2a2.com/repository/maven-snapshots
    when :
      branch :
        include :
          - develop
          - feature/*

  - name : build-and-publish-release-jar
    image : docker-registry.c2a2.com/ujar/maven:3-openjdk-17-slim
    pull : if-not-exists
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DATASOURCE_DRIVER : com.mysql.cj.jdbc.Driver
      DATASOURCE_URL : jdbc:mysql://db:3306/sa_test_db?serverTimezone=UTC&rewriteBatchedStatements=true&characterEncoding=UTF-8
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
      SONAR_HOST :
        from_secret : SONAR_HOST
      SONAR_TOKEN :
        from_secret : SONAR_TOKEN
    commands :
      - mvn clean compile test-compile -P default -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      #- mvn pmd:check -P default -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      #- mvn com.github.spotbugs:spotbugs-maven-plugin:check -P default -Dspotbugs.xmlOutput=true -Dspotbugs.failOnError=true -Dspotbugs.includeTests=true -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=ujar-org:bs-dst-k8s-bookingdb -B -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn deploy -P default -DskipTests=true -Dcheckstyle.skip=true -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD -DaltDeploymentRepository=ujar-releases-repository::default::https://nexus.c2a2.com/repository/maven-releases
    when :
      ref :
        - refs/tags/*

  - name : build-container-snapshot-init-container-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./init-container-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-init-container-service
      registry : docker-registry.c2a2.com
      tags :
        - latest
    when :
      branch :
        include :
          - develop
          - feature/*

  - name : build-container-snapshot-edge-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./edge-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-edge-service
      registry : docker-registry.c2a2.com
      tags :
        - latest
    when :
      branch :
        include :
          - develop
          - feature/*

  - name : build-container-snapshot-dashboard-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./dashboard-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-dashboard-service
      registry : docker-registry.c2a2.com
      tags :
        - latest
    when :
      branch :
        include :
          - develop
          - feature/*

  - name : build-container-snapshot-importer-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./importer-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-importer-service
      registry : docker-registry.c2a2.com
      tags :
        - latest
    when :
      branch :
        include :
          - develop
          - feature/*

  - name : build-container-release-init-container-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./init-container-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-init-container-service
      registry : docker-registry.c2a2.com
      tags :
        - 0.1.0
    when :
      ref :
        - refs/tags/*

  - name : build-container-release-edge-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./edge-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-edge-service
      registry : docker-registry.c2a2.com
      tags :
        - 0.1.0
    when :
      ref :
        - refs/tags/*

  - name : build-container-release-dashboard-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./dashboard-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-dashboard-service
      registry : docker-registry.c2a2.com
      tags :
        - 0.1.0
    when :
      ref :
        - refs/tags/*

  - name : build-container-release-importer-service
    image : plugins/docker
    settings :
      dockerfile : .drone/c2a2/Dockerfile
      context : ./importer-service/
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/bs-dst-k8s-bookingdb-importer-service
      registry : docker-registry.c2a2.com
      tags :
        - 0.1.0
    when :
      ref :
        - refs/tags/*

services :
  - name : db
    image : mysql:5.7.39
    environment :
      MYSQL_DATABASE : sa_test_db
      MYSQL_USER : sa_test
      MYSQL_PASSWORD : sa_test
      MYSQL_ROOT_PASSWORD : sa_root
      TZ : UTC
